/**
 * @File Name          : test.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 3/29/2020, 7:15:16 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    3/29/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class test {
    public test() {
//test for CI.
//VS-》git -》scrach-》productdddffffgggg
//ddd
//0328fffff

//0328fflast test
//from other pc
    }
}
