/**
 * @File Name          : test.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 3/30/2020, 8:13:08 AM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    3/29/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class test {
    public test() {
//test for CI.
//VS-》git -》scrach-》productdddffffgggg
//ddd
//0328fffff
//0328fflast tests
//test new user
//other pc new user
//other pc new userddd
    }
    }